name: traffic-sign-env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - pip
  - pip:
      - opencv-python
      - pillow
